<?php
/**
 * Short description for file
 *
 * Long description for file (if any)...
 *
 * @category   Zend
 * @package    Zend_Training
 * @subpackage ProductList
 * @copyright  Copyright (c) 2018 ecommistry (http://www.ecommistry.com)
 * @license    http://framework.zend.com/license   BSD License
 * @version    Release: 1.0
 * @link       http://framework.zend.com/package/PackageName
 * @since      Class available since Release 1.0
 */
?>

<div class="product-list-container">
    <div class="page-title title-buttons">
        <h1><?php echo $this->getTitle(); ?></h1>
    </div>
    <div class="product-list">
        <?php echo $this->getChildHtml('productlist_list'); ?>
    </div>
</div>
