<?php
/**
 * Recommended Product list template
 *
 * Adapted form rwd_default Magento Product List Template
 *
 * @category   Zend
 * @package    Zend_Training
 * @subpackage ProductList
 * @copyright  Copyright (c) 2018 ecommistry (http://www.ecommistry.com)
 * @license    http://framework.zend.com/license   BSD License
 * @version    Release: 1.0
 * @link       http://framework.zend.com/package/PackageName
 * @since      Class available since Release 1.0
 */
?>
<?php
/**
 * Recommended Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
/* @var $this Mage_Catalog_Block_Product_List */
?>
<?php
$_productCollection = $this->getLoadedProductCollection();

$this->getChild('productlist_grid')->setProductCollection(
    $_productCollection
);

$this->getChild('productlist_slider')->setProductCollection(
    $_productCollection
);

?>
<?php if (!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__(
            'There are no products matching the selection.'
        ) ?></p>
<?php else: ?>
    <div class="category-products">
        <?php
        echo $this->getToolbarHtml();
        // List mode
        if ($this->getMode() !== 'slider') {
            // Grid Mode
            echo $this->getChildHtml('productlist_grid', false);
        } else {
            // Slider Mode
            echo $this->getChildHtml('productlist_slider', false);
        }
        ?>
        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>
    </div>
<?php endif; ?>
<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}
?>
