<?php
/**
 * Product List Slider
 *
 * Slider which uses third party JS Slick and the grid layout is adapted
 * from the rwd_default layout.
 *
 * @category   Zend
 * @package    Zend_Training
 * @subpackage ProductList
 * @copyright  Copyright (c) 2018 ecommistry (http://www.ecommistry.com)
 * @license    http://framework.zend.com/license   BSD License
 * @version    Release: 1.0
 * @link       http://framework.zend.com/package/PackageName
 * @since      Class available since Release 1.0
 */
$_productCollection = $this->getProductCollection();
$_helper = $this->helper('catalog/output');

?>

<?php $_collectionSize = $_productCollection->count() ?>
<?php $_columnCount = $this->getColumnCount(); ?>
<div class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
    <?php $i = 0;
    foreach ($_productCollection as $_product): ?>
        <?php /*if ($i++%$_columnCount==0): ?>
            <?php endif*/ ?>
        <div class="item<?php if (($i - 1) % $_columnCount
            === 0
        ): ?> first<?php elseif ($i % $_columnCount
            === 0
        ): ?> last<?php endif; ?>">
            <a href="<?php echo $_product->getProductUrl() ?>"
               title="<?php echo $this->stripTags(
                   $this->getImageLabel($_product, 'small_image'),
                   null, true
               ) ?>" class="product-image-slider">
                <?php $_imgSize = 300; ?>
                <img id="product-collection-image-<?php echo $_product->getId(
                ); ?>"
                     src="<?php echo $this->helper('catalog/image')
                         ->init($_product, 'small_image')->resize(
                             $_imgSize
                         ); ?>"
                     alt="<?php echo $this->stripTags(
                         $this->getImageLabel(
                             $_product, 'small_image'
                         ), null, true
                     ) ?>"/>
            </a>
            <div class="product-slider-info">
                <h2 class="product-name"><a
                            href="<?php echo $_product->getProductUrl() ?>"
                            title="<?php echo $this->stripTags(
                                $_product->getName(), null, true
                            ) ?>"><?php echo $_helper->productAttribute(
                            $_product, $_product->getName(), 'name'
                        ) ?></a></h2>
                <?php
                // Provides extra blocks on which to hang some features for products in the list
                // Features providing UI elements targeting this block will display directly below the product name
                if ($this->getChild('name.after')) {
                    $_nameAfterChildren = $this->getChild(
                        'name.after'
                    )->getSortedChildren();
                    foreach (
                        $_nameAfterChildren as $_nameAfterChildName
                    ) {
                        $_nameAfterChild = $this->getChild(
                            'name.after'
                        )->getChild($_nameAfterChildName);
                        $_nameAfterChild->setProduct($_product);
                        echo $_nameAfterChild->toHtml();
                    }
                }
                ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <?php if ($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml(
                        $_product, 'short'
                    ) ?>
                <?php endif; ?>
                <div class="actions">
                    <?php if (!$_product->canConfigure()
                        && $_product->isSaleable()
                    ): ?>
                        <button type="button"
                                title="<?php echo $this->quoteEscape(
                                    $this->__('Add to Cart')
                                ) ?>" class="button btn-cart"
                                onclick="setLocation('<?php echo $this->getAddToCartUrl(
                                    $_product
                                ) ?>')">
                                        <span><span><?php echo $this->__(
                                                    'Add to Cart'
                                                ) ?></span></span></button>
                    <?php elseif ($_product->getStockItem()
                        && $_product->getStockItem()->getIsInStock()
                    ): ?>
                        <a title="<?php echo $this->quoteEscape(
                            $this->__('View Details')
                        ) ?>" class="button"
                           href="<?php echo $_product->getProductUrl(
                           ) ?>"><?php echo $this->__(
                                'View Details'
                            ) ?></a>
                    <?php else: ?>
                        <p class="availability out-of-stock">
                                        <span><?php echo $this->__(
                                                'Out of stock'
                                            ) ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')
                            ->isAllow()
                        ) : ?>
                            <li><a href="<?php echo $this->helper(
                                    'wishlist'
                                )->getAddUrl($_product) ?>"
                                   class="link-wishlist"><?php echo $this->__(
                                        'Add to Wishlist'
                                    ) ?></a></li>
                        <?php endif; ?>
                        <?php if ($_compareUrl
                            = $this->getAddToCompareUrl($_product)
                        ): ?>
                            <li><span class="separator">|</span> <a
                                        href="<?php echo $_compareUrl ?>"
                                        class="link-compare"><?php echo $this->__(
                                        'Add to Compare'
                                    ) ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </div>
        <?php /*if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            <?php endif*/ ?>
    <?php endforeach ?>
</div>

<!-- Slick Slider Javascript -->
<script type="text/javascript">
    jQuery(document).ready(function () {
        jQuery('.products-grid').slick({
            dots: true,
            arrows: true,
            slidesToShow: 2,
            slidesToScroll: 2
        });
    })
</script>
